name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} (RubyGems ${{ matrix.rubygems }}, Bundler ${{ matrix.bundler }})
    strategy:
      matrix:
        ruby:
          - "3.2.2"
          - "jruby-9.4"
          - "truffleruby-23"
        rubygems:
          - "3.4.20"
        bundler:
          - "2.4.20"

    env:
      BUNDLER_VERSION: ${{ matrix.bundler }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Update rubygems
        run: gem update --system=${{ matrix.rubygems }}
      - name: Run the default task
        run: bin/rake

  all:
    name: Test All
    needs: [build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - run: /bin/${{ (needs.build.result == 'success' || needs.build.result == 'skipped') }}
